version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

workflows:
    example-workflow:
      jobs:
        - build-and-test
        - aws-ecr/build-and-push-image:
            requires:
              - build-and-test
            repo: ${APP_NAME}
            role-arn: ${AWS_ECS_ARN} 
            region: ${AWS_DEFAULT_REGION}
            filters:
              #tags:
                #only: /v(\d+)\.[0-9]?[0-9]\.[0-9]?[0-9]$/ # 버전 정규식 v1.0.0의 형태
              branches:
                only:
                  - master

