version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
    example-workflow:
      jobs:
        - aws-ecr/build-and-push-image:
            repo: ${APP_NAME}
            role-arn: ${AWS_ECS_ARN} 
            region: ${AWS_DEFAULT_REGION} 